---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: docker.io/library/neo4j:5.19-community
          env:
            - name: NEO4J_AUTH
              value: none
            - name: NEO4J_PLUGINS
              value: >
                [
                "apoc",
                "apoc-extended"
                ]
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
          ports:
            - name: http
              protocol: TCP
              containerPort: 7474
            - name: bolt
              protocol: TCP
              containerPort: 7687
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem
