# database secret 관리
apiVersion: v1
kind: Secret
metadata:
  name: dreamcatcher-database
  namespace: computer-system-team-07 # 우리팀 네임스페이스
  # helm 관리 정보
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "dreamcatcher"
    meta.helm.sh/release-namespace: "computer-system-team-07"
type: Opaque
stringData:
  # password: <your-password>
  password: "<your-password>"
---
# OpenAI api secret 관리
apiVersion: v1
kind: Secret
metadata:
  name: openai
  # helm 관리 정보
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "openai"
    meta.helm.sh/release-namespace: "computer-system-team-07"
stringData:
  # OPENAI_API_KEY: "your-openai-api-key"
  OPENAI_API_KEY: "your-openai-api-key"
